"""
CLI Runner for the research agent Run the agent directly
Usage:
default - clean output show final report only 

verbose - show every node state change and tool call

step-through - pause after each node so you can inspect state

stream - Prints tokens as they are generated by synthesis_node
"""

from __future__ import annotations
import argparse
import asyncio
import json
import sys
import textwrap
import time
import uuid
from typing import Any

sys.path.insert(0,".")

from agent.graph import build_research_graph
from agent.state import create_itital_state, ResearchAgentState

_USE_COLOR= sys.stdout.isatty()

def _c(text:str, code: str)-> str:
    return f"\033{code} {text}\033[0m" if _USE_COLOR else text

def cyan(t): return _c(t,"36")
def green(t): return _c(t,"32")
def yellow(t): return _c(t,"33")
def red(t): return _c(t,"31")
def bold(t): return _c(t,"1")
def dim(t): return _c(t,"2")

def print_divider(char: str="-", width: int=70)->None:
    print(dim(char*width))

def print_section(title:str)-> None:
    print()
    print_divider("=")
    print(bold(f" {title}"))
    print_divider("=")

def print_node_header(node_name: str, elapsed: float)->None:
    print()
    print_divider()
    print(f" {cyan('NODE')} {bold(node_name)}"
          f" {dim(f'+{elapsed:.1f}s')}"
          )
    print_divider()

def print_state_diff(before:dict, after:dict, verbose: bool)->None:

    """Print which state field change after node ran
    If verbose value is True prints the new value."""
    changed_field=[]

    for key in after:
        before_val= before.get(key)
        after_val= after.get(key)

        if before_val!=after_val:
            changed_field.append(key)

    if not changed_field:
        print(dim(" (no state changes)"))
        return
    for field in changed_field:
        val= after[field]

        #format value display
        if isinstance(val, list):
            display= f"[{len(val)}] items"
        elif isinstance(val, dict):
            display= f"{{...{len(val)}keys}}"
        elif isinstance(val, str) and len(val)>80:
            display= f'"{val[:77]}...'
        elif isinstance(val, str):
            display= f'"{val}"'
        else:
            display= str(val)

        print(f" {green('+')} {bold(field)}: {display}")

        if verbose:
            if field== "search_result" and isinstance(val, list):
                for i, r in enumerate(val[-3:],1):
                    scoreprint= f"score= {r.get('score',0):.2f}"
                    sourceprint= f"source= {r.get('source','?')}"
                    print(
                        f"    {dim(f'[{i}]')}"
                        f"{r.get('title', '')[:50]}"
                        f"{r.get('url','')[:40]}"
                        f"{yellow(scoreprint)}"
                        f"{dim(sourceprint)}"
                    )
            
            elif field== "plan" and isinstance(val,dict):
                for t in val.get("subtask", []):
                    stepprint= f"step {t.get('step_index')}"
                    print(
                        f" {dim(stepprint)}"
                        f" {t['task_type']}"
                        f" {dim(t['query'][:60])}"
                    )

            elif field== "reflections" and isinstance(val, list) and val:
                last= val[-1]

                print(f" {dim('decession:')} {yellow(last.get('decession','?'))}")
                if last.get("critique"):
                    print(f" {dim('critique')}"
                          f"{last['critique'][:100]}")
                    
            elif field== "node_metrics" and isinstance(val,list) and val:
                last= val[-1]

                print(f" {dim('tokens:')} "
                      f"prompts= {last.get('prompt_tokens',0)} "
                      f"completion= {last.get('completion_tokens',0)} "
                      f"duration={last.get('duration_ms', 0):.0f}ms")

def print_summary(final_state: ResearchAgentState, total_elapsed: float)-> None:
    """
    Print a cost/performance summary after the run completes.
    Uses node_metrics accumulated in state,
    """

    metrics= final_state.get("node_metrics",[])

    total_prompt= sum(m.get("prompt_tokens", 0) for m in metrics)
    total_completion= sum(m.get("completion_tokens",0) for m in metrics)
    total_tokens= total_prompt+ total_completion

    cost_usd= (total_prompt/1_000_000 *2.50) + (total_completion /1_000_000*10.00)

    print_section("Run Summary")

    print(f" {bold('Total time:')} {total_elapsed:.1f}s")
    print(f" {bold('Prompt Tokens:')} {total_prompt:,}")
    print(f" {bold('Complettion Tokens:')} {total_completion:,}")
    print(f" {bold('Total Tokens:')} {total_tokens:,}")
    print(f" {bold('Estimated Cost:')} ${cost_usd}")
    print(f" {bold('Search Results:')} {len(final_state.get('search_results',[]))}")
    print(f" {bold('Document Read')} {len(final_state.get('documents_read',[]))}")
    print(f" {bold('Reflections:')} {len(final_state.get('reflections',[]))}")

    if metrics:
        print()
        print(f" {bold('Pre-node breakdown:')}")

        for m in metrics:
            name= m.get("node_name","?")
            pt= m.get("prompt_tokens",0)
            ct= m.get("completion_tokens",0)
            dur= m.get("duration_ms",0)

            if pt>0 or ct>0:
                print(f" {name:<25}"
                      f"prompt= {pt:<6}"
                      f"completion={ct:<6}"
                      f"{dim(f'{dur:.0f}ms')}")
                
async def run_agent(query:str,
              verbose: bool=False,
              step_through:bool=False,
              stream:bool=False)-> ResearchAgentState:
    """Invoke the research agent and return the final state
    Args: 
        query: The user question /research question
        verbose: Show detailed state difference after each node.
        step_through: Pause after each node press enter to continue
        stream: Stream Synthesis token as they genearated.

    Returns:
        The final ResearchAgentstate after the graph ends.
    """

    session_id= str(uuid.uuid4())

    graph= build_research_graph()

    initial_state= create_itital_state(query=query, session_id=session_id)

    config= {
        "configurable": {
            "thread_id": session_id
        }
    }

    print_section(f" Research Agent [session: {session_id}]")

    print(f"{bold('Query')} {query}")
    print(f" {bold('Mode:')}  "
          f"{'verbose ' if verbose else ''}"
          f"{'step ' if step_through else ''}"
          f"{'stream ' if stream else ''}"
          f"{'default ' if not any([verbose, step_through, stream]) else ''}")
    run_start= time.monotonic()
    prev_state: dict={}
    node_count=0

    
    if stream:
        print_section("Streaming Output")
        final_state= None
        async for event in graph.astream_events(initial_state,config=config,version="v2"):
            kind= event.get("event")
            name= event.get("name", "")

            if kind== "on_chain_start" and name in {"intent_node","planner_node",
                                                    "reflection_node", "synthesis_node",
                                                    "memory_update_node","error_node",}:
                elapsed= time.monotonic()- run_start
                print(f"{cyan('Start')} {bold(name)} {dim(f'+{elapsed:.1f}s')}")

            elif kind== "on_chat_model_stream" and "synthesis" in str(event.get("metadata",{})
                                                                      ):
                chunk= event.get("data",{}).get("chunk")
                if chunk and hasattr(chunk, "content") and chunk.content:
                    print(chunk.content, end="", flush=True)

            elif kind=="on_chain_end":
                output= event.get("data",{}).get("output",{})

                if isinstance(output,dict) and "is_complete" in output:
                    final_state= output
        
        print()
        checkpoint= await graph.aget_state(config=config)
        final_state= checkpoint.values if checkpoint else {}
    
    # Step / verbose mode - uses astream for node by node output

    else:
        final_state={}

        async for step in graph.astream(initial_state, config=config, stream_mode="updates"):
            elapsed= time.monotonic()- run_start
            node_count+=1

            for node_name, state_update in step.items():
                print_node_header(node_name=node_name, elapsed=elapsed)
                print_state_diff(prev_state, state_update, verbose)

                prev_state.update(state_update)

                if step_through:
                    try: 
                        input(f"\n {dim('Press Enter to continue...')}")

                    except (EOFError, KeyboardInterrupt):
                        print("\n Interrupted")
                        break
            checkpoint= await graph.aget_state(config)
            final_state= checkpoint.values if checkpoint else prev_state

        total_elapsed= time.monotonic()- run_start

        print_section("Research Report")

        final_response= final_state.get("final_response","")
        error= final_state.get("error","")

        if error and not final_response:
            print(red(f" Error: {error}"))
        
        elif final_response:
            wrapped= textwrap.fill(
                final_response,
                width=70,
                subsequent_indent=" "
            )

            for para in final_response.split("\n\n"):
                print(textwrap.fill(para.strip(),width=70, initial_indent=" ", subsequent_indent=" "))

                print()
        else:
            print(yellow(" No response generated"))

        print_summary(final_state=final_state, total_elapsed=total_elapsed)

        return final_state
    

def main()-> None:
    parser= argparse.ArgumentParser(
        description="Run the Research agent from the CLI",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""
        Examples:
                python scripts/run_agent.py "what is Langgraph?"
                python scripts/run_agent.py "what is Langgraph?" --verbose
                python scripts/run_agent.py "what is Langgraph?" --step
                python scripts/run_agent.py "what is Langgraph?" --stream
        """)
    )
    parser.add_argument("query",
                        nargs="?",
                        default=None,
                        help="Research question prompted if not provided")
    
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Show detailsed state diffs and search results after each node",
    )
    parser.add_argument(
        "--step", "-s",
        action="store_true",
        help="Pause after each node - inspect state before continuing",
    )
    parser.add_argument(
        "--stream",
        action="store_true",
        help="Stream synthesis tokens as they are generated",
    )

    args= parser.parse_args()

    #prompt if no query provided
    query= args.query
    if not query:
        print(bold("\nResearch Agent - Interactive Mode"))
        print(dim("(Ctrl+C to exit)"))

        try: 
            query= input("Enter your research question: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nExiting.")
            sys.exit(0)

    if not query:
        print(red("Error: query can not be empty"))
        sys.exit(1)

    try:
        asyncio.run(
            run_agent(query= query, verbose=args.verbose, step_through=args.step, stream=args.stream)
        )

    except KeyboardInterrupt:
        print("\n\nInterrupted by user")
        sys.exit(0)

    except Exception as e:
        print(red(f"\nFatal error: {type(e).__name__}"))
        if args.verbose:
            import traceback
            traceback.print_exc()
        sys.exit(1)

if __name__=="__main__":
    main()
